version: '3.8'

services:
  # TimeCraft API server service
  timecraft-api:
    build: .
    ports:
      - "8080:8080"  # Map container port to host
    restart: unless-stopped  # Automatically restart if it crashes